[package]
name = "tw_any_coin"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_coin_entry = { path = "../tw_coin_entry" }
tw_coin_registry = { path = "../tw_coin_registry" }
tw_memory = { path = "../tw_memory" }
tw_misc = { path = "../tw_misc" }
