[package]
name = "tw_binance"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_bech32_address = { path = "../../tw_bech32_address" }
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_cosmos_sdk = { path = "../../tw_cosmos_sdk" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_proto = { path = "../../tw_proto" }
serde = { version = "1.0", features = ["derive"] }
