name: TWCoinTypeConfiguration
structs:
- name: TWCoinTypeConfiguration
  is_public: true
  is_class: false
  fields:
  - - unused
    - variant: u_int8_t
      is_nullable: false
  comments:
  - CoinTypeConfiguration functions
functions:
- name: TWCoinTypeConfigurationGetSymbol
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  return_type:
    variant: string
    is_nullable: false
  comments:
  - Returns stock symbol of coin
  - \param type A coin type
  - \return A non-null TWString stock symbol of coin
  - \note Caller must free returned object
- name: TWCoinTypeConfigurationGetDecimals
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  return_type:
    variant: int
    is_nullable: false
  comments:
  - Returns max count decimal places for minimal coin unit
  - \param type A coin type
  - \return Returns max count decimal places for minimal coin unit
- name: TWCoinTypeConfigurationGetTransactionURL
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  - name: transactionID
    type:
      variant: string
      is_nullable: false
  return_type:
    variant: string
    is_nullable: false
  comments:
  - Returns transaction url in blockchain explorer
  - \param type A coin type
  - \param transactionID A transaction identifier
  - \return Returns a non-null TWString transaction url in blockchain explorer
- name: TWCoinTypeConfigurationGetAccountURL
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  - name: accountID
    type:
      variant: string
      is_nullable: false
  return_type:
    variant: string
    is_nullable: false
  comments:
  - Returns account url in blockchain explorer
  - \param type A coin type
  - \param accountID an Account identifier
  - \return Returns a non-null TWString account url in blockchain explorer
- name: TWCoinTypeConfigurationGetID
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  return_type:
    variant: string
    is_nullable: false
  comments:
  - Returns full name of coin in lower case
  - \param type A coin type
  - \return Returns a non-null TWString, full name of coin in lower case
- name: TWCoinTypeConfigurationGetName
  is_public: true
  is_static: true
  params:
  - name: type
    type:
      variant: enum
      value: TWCoinType
      is_nullable: false
  return_type:
    variant: string
    is_nullable: false
  comments:
  - Returns full name of coin
  - \param type A coin type
  - \return Returns a non-null TWString, full name of coin
