name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        brew install boost ninja xcodegen
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
        tools/generate-files
    - name: Run codegen tests
      run: tools/codegen-test
    - name: Run iOS tests
      run: tools/ios-test
