[package]
name = "rustsample"
version = "0.1.0"
links = "foo"
build = "src/build.rs"
authors = ["Walelt Core"]
edition = "2021"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
