[workspace]
members = [
    "tw_encoding",
    "tw_hash",
    "tw_keypair",
    "tw_memory",
    "tw_misc",
    "tw_move_parser",
    "tw_proto",
    "wallet_core_rs",
]

[profile.wasm-release]
inherits = "release"

# Fixes an endless compilation.
[profile.wasm-release.package.curve25519-dalek]
opt-level = 1
