[workspace]
members = [
    "tw_encoding",
    "tw_hash",
    "tw_keypair",
    "tw_memory",
    "tw_misc",
    "tw_move_parser",
    "tw_proto",
    "wallet_core_rs",
]

[profile.release]
opt-level = 2
