[workspace]
members = [
    "tw_encoding",
    "tw_hash",
    "tw_keypair",
    "tw_memory",
    "tw_misc",
    "tw_move_parser",
    "tw_proto",
    "wallet_core_rs",
]

# Required by `k256` (signal: 10, SIGBUS: access to undefined memory) and `curve25519` (endless stuck) crates.
[profile.dev]
opt-level = 2
