name: Docker CI

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - tools/install-dependencies
  pull_request:
    branches: [ main ]
    paths: 
      - Dockerfile
      - tools/install-dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Dockerfile
      uses: docker/build-push-action@v1.1.0
      with:
        repository: trustwallet/wallet-core
        tags: latest
        push: false
