name: Linux CI JNI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          tools/install-sys-dependencies-linux
          tools/install-rust-dependencies
      - name: Cache internal dependencies
        id: internal_cache
        uses: actions/cache@v3
        with:
          path: build/local
          key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-dependencies') }}
      - name: Install internal dependencies
        run: |
          tools/install-dependencies
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        if: steps.internal_cache.outputs.cache-hit != 'true'

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust

      - name: Code generation
        run: |
          tools/generate-files native
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
      - name: CMake (Java, Kotlin)
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DTW_UNITY_BUILD=ON -DTW_JAVA=ON -DTW_KOTLIN=ON -GNinja
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
      - name: Build and test
        run: |
          ninja -Cbuild
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
