name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  boost:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Check boost
        run: |
          ls -lR ${BOOST_ROOT_1_72_0}
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=${BOOST_ROOT_1_72_0}
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get install ninja-build lcov
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
        tools/generate-files
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Build and test
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DBOOST_ROOT=${BOOST_ROOT_1_72_0}
        make -Cbuild
        build/tests/tests tests --gtest_output=xml
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Gather code coverage
      run: |
        sudo rm -rf coverage.info
        tools/coverage
