name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get install autoconf ninja-build pkg-config xz-utils lcov
    - name: Install internal dependencies
      run: |
        tools/install-dependencies
        tools/generate-files
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Build and test
      run: |
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
        make -Cbuild
        build/tests/tests tests --gtest_output=xml
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
    - name: Gather code coverage
      run: |
        sudo rm -rf coverage.info
        tools/coverage
