# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tag

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: '15.13.31'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}