name: Typescript CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: typescript
    - name: Build and test
      run: npm run build && npm test
      working-directory: typescript
    - name: Check if needed to publish
      run: |
        echo "::set-output name=publish::$(tools/check-version)"
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
  
  publish-npm:
    needs: build
    if: "build.steps.build.outputs.publish == true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: |
          npm ci && npm run build && npm publish
        working-directory: typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    if: "build.steps.build.outputs.publish == true"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Publish
        run: |
          npm ci && npm run build && npm publish
        working-directory: typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
